# Generated by Django 5.0.4 on 2026-04-16 08:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_type', models.CharField(choices=[('user', 'User'), ('organization', 'Organization'), ('platform_system', 'Platform System'), ('escrow', 'Escrow'), ('external', 'External')], max_length=20)),
                ('owner_type', models.CharField(max_length=20)),
                ('owner_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('currency', models.CharField(default='XAF', max_length=3)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('hold_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('active', 'Active'), ('frozen', 'Frozen'), ('closed', 'Closed')], default='active', max_length=20)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ledger_reference_id', models.CharField(max_length=30, unique=True)),
                ('idempotency_key', models.UUIDField(unique=True)),
                ('transaction_type', models.CharField(choices=[('cashin', 'Cash In'), ('cashout', 'Cash Out'), ('transfer', 'Transfer'), ('split', 'Split'), ('hold_capture', 'Hold Capture'), ('hold_release', 'Hold Release'), ('adjustment', 'Adjustment'), ('reversal', 'Reversal')], max_length=30)),
                ('platform_id', models.UUIDField()),
                ('source', models.CharField(max_length=30)),
                ('source_reference_id', models.UUIDField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(default='completed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ledger_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Hold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('captured', 'Captured'), ('released', 'Released'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('reason', models.CharField(max_length=50)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('idempotency_key', models.UUIDField(unique=True)),
                ('expires_at', models.DateTimeField()),
                ('captured_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holds', to='accounts.account')),
            ],
            options={
                'db_table': 'holds',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashoutRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(default='XAF', max_length=3)),
                ('destination_provider', models.CharField(max_length=30)),
                ('destination_details', models.JSONField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('payment_tx_id', models.UUIDField(blank=True, null=True)),
                ('idempotency_key', models.UUIDField(unique=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashout_requests', to='accounts.account')),
                ('hold', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.hold')),
            ],
            options={
                'db_table': 'cashout_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SplitRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform_id', models.UUIDField()),
                ('name', models.CharField(max_length=100)),
                ('rules', models.JSONField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'split_rules',
                'unique_together': {('platform_id', 'name')},
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=6)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='accounts.account')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='accounts.ledgertransaction')),
            ],
            options={
                'db_table': 'ledger_entries',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['account', 'created_at'], name='ledger_entr_account_14b5c0_idx')],
            },
        ),
    ]
