# Generated by Django 5.0.4 on 2026-04-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_cashoutrequest_idempotency_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashoutrequest',
            name='payment_tx_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='hold',
            name='reference_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='ledgertransaction',
            name='source_reference_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
