services:
  media:
    build: .
    container_name: agt_media_simulator
    restart: unless-stopped
    ports:
      - "7003:7003"
    volumes:
      - ./uploads:/app/uploads
    networks:
      - agt_network

networks:
  agt_network:
    external: true
    name: agt_network