# Generated by Django 5.0.4 on 2026-04-15 20:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform_id', models.UUIDField(db_index=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('system_prompt', models.TextField(blank=True, null=True)),
                ('fallback_message', models.TextField(default="Je n'ai pas compris. Pouvez-vous reformuler ?")),
                ('human_transfer_after', models.IntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationFlow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('trigger_intent', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='bots.bot')),
            ],
            options={
                'db_table': 'conversation_flows',
            },
        ),
        migrations.CreateModel(
            name='FlowNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('message', 'Message'), ('question', 'Question'), ('condition', 'Condition'), ('action', 'Action')], max_length=20)),
                ('content', models.JSONField()),
                ('branches', models.JSONField(blank=True, null=True)),
                ('position', models.IntegerField(default=0)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='bots.conversationflow')),
                ('next_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bots.flownode')),
            ],
            options={
                'db_table': 'flow_nodes',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Intent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('response', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intents', to='bots.bot')),
            ],
            options={
                'db_table': 'intents',
                'unique_together': {('bot', 'name')},
            },
        ),
        migrations.CreateModel(
            name='IntentKeyword',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=100)),
                ('weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='bots.intent')),
            ],
            options={
                'db_table': 'intent_keywords',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kb_categories', to='bots.bot')),
            ],
            options={
                'db_table': 'knowledge_categories',
                'unique_together': {('bot', 'name')},
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBaseEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kb_entries', to='bots.bot')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bots.knowledgecategory')),
            ],
            options={
                'db_table': 'knowledge_base_entries',
            },
        ),
        migrations.CreateModel(
            name='TransferLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conversation_id', models.UUIDField()),
                ('chat_transfer_id', models.UUIDField(blank=True, null=True)),
                ('user_id', models.UUIDField()),
                ('reason', models.CharField(blank=True, max_length=50, null=True)),
                ('bot_history', models.JSONField(blank=True, null=True)),
                ('context', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(default='sent', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_logs', to='bots.bot')),
            ],
            options={
                'db_table': 'transfer_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AiProviderConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=50)),
                ('api_key_encrypted', models.TextField(blank=True, null=True)),
                ('base_url', models.CharField(blank=True, max_length=500, null=True)),
                ('temperature', models.DecimalField(decimal_places=2, default=0.7, max_digits=3)),
                ('max_tokens', models.IntegerField(default=1000)),
                ('purpose', models.CharField(choices=[('conversation', 'Conversation'), ('rag', 'RAG'), ('translation', 'Translation'), ('fallback', 'Fallback')], max_length=30)),
                ('priority', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('circuit_breaker_threshold', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_providers', to='bots.bot')),
            ],
            options={
                'db_table': 'ai_provider_configs',
                'unique_together': {('bot', 'provider', 'purpose')},
            },
        ),
        migrations.CreateModel(
            name='BotChannel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.JSONField(blank=True, null=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='bots.bot')),
            ],
            options={
                'db_table': 'bot_channels',
                'unique_together': {('bot', 'channel')},
            },
        ),
        migrations.CreateModel(
            name='BotConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('config_key', models.CharField(max_length=100)),
                ('config_value', models.TextField()),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='bots.bot')),
            ],
            options={
                'db_table': 'bot_configs',
                'unique_together': {('bot', 'config_key')},
            },
        ),
        migrations.CreateModel(
            name='BotStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_messages', models.IntegerField(default=0)),
                ('resolved_count', models.IntegerField(default=0)),
                ('fallback_count', models.IntegerField(default=0)),
                ('human_transfer_count', models.IntegerField(default=0)),
                ('layer1_count', models.IntegerField(default=0)),
                ('layer2_count', models.IntegerField(default=0)),
                ('layer3_count', models.IntegerField(default=0)),
                ('top_intents', models.JSONField(blank=True, null=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='bots.bot')),
            ],
            options={
                'db_table': 'bot_stats',
                'unique_together': {('bot', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ConversationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conversation_id', models.UUIDField(db_index=True)),
                ('sender_id', models.UUIDField()),
                ('channel', models.CharField(max_length=30)),
                ('user_message', models.TextField()),
                ('bot_response', models.TextField()),
                ('layer_used', models.CharField(max_length=30)),
                ('intent_detected', models.CharField(blank=True, max_length=100, null=True)),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('provider_used', models.CharField(blank=True, max_length=30, null=True)),
                ('tokens_used', models.IntegerField(blank=True, null=True)),
                ('processing_time_ms', models.IntegerField()),
                ('is_resolved', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_logs', to='bots.bot')),
            ],
            options={
                'db_table': 'conversation_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['bot', 'created_at'], name='conversatio_bot_id_33ccaf_idx'), models.Index(fields=['bot', 'is_resolved'], name='conversatio_bot_id_63d8fb_idx')],
            },
        ),
    ]
